# @package _global_
# VQ-VAE tokenization: pretrained encoder + VQ bottleneck
# Requires: pre-train VQ-VAE first, then copy best_val.pt to env.vq_checkpoint_path
defaults:
  - override /data: h5_tokens

classifier:
  model:
    tokenizer:
      name: pretrained
      # Pass both checkpoint paths - PretrainedTokenizer will auto-select based on cont_features
      checkpoint_path_5vec: ${env.vq_checkpoint_path_5vec}
      checkpoint_path_4vec: ${env.vq_checkpoint_path_4vec}
      model_type: vq
