defaults:
  # --- Environment paths (local vs HPC) ---
  - env: stoomboot  # Default to stoomboot; run locally with `env: local`

  # --- Hydra & logging ---
  - hydra: run_single
  - logging: wandb_offline

  # --- Metadata schema ---
  - meta: default

  # --- Data source ---
  - data: h5_tokens

  # --- General trainer config (for non-phase-specific code) ---
  - general/trainer: default      # top-level trainer for general code, this just linkes to the general/trainer/default.yaml file. only used when loop (keep in mind that this is the default loop) is overridden.

  # --- Phase 1 component configs ---
  - phase1/encoder: mlp           # encoder architecture and hyperparameters
  - phase1/decoder: mlp           # decoder architecture and hyperparameters
  - phase1/latent_space: none       # latent space configuration (VQ, none, etc.)
  - phase1/trainer: ae            # phase1-specific training hyperparameters
  - phase1/experiment: null


  # --- Phase 2 component configs ---
  - classifier/trainer: default
  - classifier/model: transformer
  - classifier/experiment: null


  - _self_

# --- High-level dispatcher key ---
loop: transformer_classifier
